version: '3.9'
services:
  geoserver1:
    build:
      context: .
      dockerfile: tomcat/Dockerfile
    image: localhost/tornanext-geoserver1:${DOCKER_REPOSITORY_IMAGE_TAG:-latest}
    ports:
      - "8081:8080"
    volumes:
      - ./services/geoserver1/data/release:/usr/local/tomcat/webapps/geoserver/data
  geoserver2:
    build:
      context: .
      dockerfile: tomcat/Dockerfile
    image: localhost/tornanext-geoserver2:${DOCKER_REPOSITORY_IMAGE_TAG:-latest}
    ports:
      - "8082:8080"
    volumes:
      - ./services/geoserver2/data/release:/usr/local/tomcat/webapps/geoserver/data