services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    security_opt:
      - "label:disable"
    ulimits:
      nofile:
        soft: 10240
        hard: 10240
    volumes:
      - mvn-cache:/home/vscode/.m2
      - ..:/workspace
volumes:
  mvn-cache:
