name: GHCR Build Service Workflow

on:
  workflow_call:
    inputs:
      service_name:
        description: Service name
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Make service image
        run: |
          printenv | sort
          java --version
          mvn --version
          mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout
          # make build SERVICE_NAME=${{ inputs.service_name }}