name: GHCR Build Service Workflow

on:
  workflow_call:
    inputs:
      service_name:
        description: Service name
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: setup-cache-${{ runner.os }}-${{ hashFiles('**/pom.xml')-${{ hashFiles('services/${{ input.service_name }}/config.env' )}}
      - name: Make service image
        run: |
          java --version
          mvn --version
          make build SERVICE_NAME=${{ inputs.service_name }}