name: GHCR Build Service Workflow

on:
  workflow_call:
    inputs:
      service_name:
        description: Service name
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          submodules: true
      - name: Checkout GeoServer version
        run: |
          make geoserver_init SERVICE_NAME=${{ inputs.service_name }}
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          cache: maven
          distribution: temurin
          java-version: 11
      - name: Make service image
        run: |
          java --version
          mvn --version
          make build SERVICE_NAME=${{ inputs.service_name }}