name: Service Geoserver1 Workflow

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ghcr_build_service.yml
      - .github/workflows/service_geoserver1.yml
      - Makefile
      - services/geoserver1
      - tomcat
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ghcr_build_service.yml
      - .github/workflows/service_geoserver1.yml
      - Makefile
      - services/geoserver1
      - tomcat
  workflow_dispatch:

jobs:
  Release:
    uses: ./.github/workflows/ghcr_build_service.yml
    with:
      service_name: geoserver1
