name: Service Geoserver2 Workflow

on:
  push:
    branches:
      - main
    paths:
      - Makefile
      - services/geoserver2
      - tomcat
  pull_request:
    branches:
      - main
    paths:
      - Makefile
      - services/geoserver2
      - tomcat
  workflow_dispatch:

jobs:
  Release:
    uses: ./.github/workflows/ghcr_build_service.yml
    with:
      service_name: geoserver2
